services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jobboard_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
      - "5173:5173"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: jobboard_mysql
    environment:
      MYSQL_DATABASE: jobboard
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: jobboard
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
